# General
maven_group = mirsario
root_package = mirsario.cameraoverhaul
archives_base_name = CameraOverhaul

# Mod Properties
mod.id = cameraoverhaul
mod.name = CameraOverhaul
mod.version = 2.0.5
mod.version_type = release
mod.description =\
  CameraOverhaul is a highly configurable clientside Minecraft mod that attempts to improve overall satisfaction of the game through the introduction of various camera rotations, emphasizing on the player's movement and improving visual feedback.\n\
  Strafing and turning around will tilt the camera sideways. Jumping, falling, and moving forward or backwards will affect the camera's pitch.\n\
  Nearby explosions will shake the screen, and ceasing movement for enough time will cause the camera to gently sway around while waiting for your input.\n\
  \n\
  Configurable through GUIs as well as the '.minecraft/config/cameraoverhaul.toml' file.
mod.authors =\
  Mirsario
mod.contributors =\
  altrisi\n\
  sam-mccarthy\n\
  IMS212\n\
  TheMrEngMan\n\
  Lucanoria\n\
  mpustovoi\n\
  TheLegendofSaram\n\
  stabery\n\
  czfortythree\n\
  Xinyang-Gao
mod.forgeupdatecheckurl = https://github.com/Mirsario/Minecraft-CameraOverhaul/blob/dev/meta/ForgeUpdateCheck.json?raw=true

# Contact (Mod)
contact.homepage = https://modrinth.com/mod/cameraoverhaul
contact.sources = https://github.com/Mirsario/Minecraft-CameraOverhaul
contact.issues = https://github.com/Mirsario/Minecraft-CameraOverhaul/issues
contact.modrinth = https://modrinth.com/mod/cameraoverhaul
contact.curseforge = https://curseforge.com/minecraft/mc-mods/cameraoverhaul
# Contact (Author)
contact.email = me@mirsar.io
contact.discord = https://discord.gg/RNGq9N8
contact.patreon = https://patreon.com/Mirsario
contact.youtube = https://youtube.com/@Mirsario

# Game
mc.type = [VERSIONED]
mc.version = [VERSIONED]
mc.version_range = [VERSIONED]
mc.displayed_range = [VERSIONED]

# Dependency Ranges
deps.fabric_loader = 0.15.11
deps.cloth_config = [VERSIONED]
deps.modmenu = [VERSIONED]
deps.mixin_extras = 0.5.0-beta.5

# Publishing
publish.enabled = true
publish.modrinth.id = m0oRwcZx
publish.curseforge.id = 423602
publish.github.repository = Mirsario/Minecraft-CameraOverhaul
publish.github.branch = dev
publish.github.format =\
{{changelog}}\n\
\n\
## Links:\n\
- [Download from **Modrinth** \ud83d\udfe2](https://modrinth.com/mod/cameraoverhaul/versions)\n\
- [Download from **CurseForge** \ud83d\udd25](https://curseforge.com/minecraft/mc-mods/cameraoverhaul/files)\n\
- [Chat & ask questions on **Discord** \ud83d\udcac](https://discord.gg/RNGq9n8)\n\
- [Support me on **Patreon** \u2764\ufe0f](https://patreon.com/Mirsario)
publish.discord.username = mirsar.io
publish.discord.avatar = https://2.gravatar.com/avatar/0d01535c027cc9d613a03f4d6eb77dd00abae05b9a756c9bb02a4a926d3107af
publish.discord.format =\
# :camera: Minecraft - Camera Overhaul v{{version}}\n\
{{changelog}}\n\
**Download:**\n\
<:modrinth:1334248141024923811> [**Modrinth**](https://modrinth.com/mod/cameraoverhaul) \
<:curseforge:1334248138214477985> [**Curseforge**](<https://curseforge.com/minecraft/mc-mods/cameraoverhaul>) \
<:github:1334248135651885119> [**GitHub**](<https://github.com/Mirsario/Minecraft-CameraOverhaul>)

# Gradle Options
systemProp.file.encoding=utf-8
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true