# Game
mc.type = release
mc.version = 1.19
mc.version_range = >=1.19 <1.19.3
mc.displayed_range = [1.19-1.19.2]

# Loader
loader.id = fabric
    #deps.yarn_mappings = 1.19+build.4

# Dependencies
mods.clothconfig.ref = 7.0.69
mods.clothconfig.range = >=7.0.69
mods.modmenu.ref = 4.0.0
mods.modmenu.range = >=4.0.0
