# Game
mc.type = release
mc.version = 1.19.3
mc.version_range = >=1.19.3 <1.20.6
mc.displayed_range = [1.19.3-1.20.5]

# Loader
loader.id = fabric
loom.platform = fabric

# Dependencies
mods.clothconfig.ref = 9.0.94
mods.clothconfig.range = >=9.0.94
mods.modmenu.ref = 5.0.0
mods.modmenu.range = >=5.0.0
