# Game
mc.type = release
mc.version = 1.14.4
mc.version_range = >=1.14 <1.15
mc.displayed_range = [1.14.x]

# Loader
loader.id = fabric
    #deps.yarn_mappings = 1.14.4+build.18

# Dependencies
mods.clothconfig.ref = 1.8
mods.clothconfig.range = >=1.8
mods.modmenu.ref = 1.10.5
mods.modmenu.range = >=1.7
