# Game
mc.type = release
mc.version = 1.15
mc.version_range = >=1.15 <1.17
mc.displayed_range = [1.15-1.16]

# Loader
loader.id = fabric
    #deps.yarn_mappings = 1.15+build.2

# Dependencies
mods.clothconfig.ref = 2.14.2
mods.clothconfig.range = >=2.14.2
mods.modmenu.ref = 1.10.5
mods.modmenu.range = >=1.10.5
